[package]
name = "rust_template"
version = "0.1.0"
authors = ["USER"]  #CHANGE USER TO YOU
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpi_embedded = "0.0.5"
